---
title: Mayor @billpeduto tweets
author: Conor Tompkins
date: '2018-03-04'
slug: mayor-billpeduto-tweets
categories:
  - Pittsburgh
  - R
tags:
  - Pittsburgh
  - R Markdown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE,
                      message = FALSE,
                      warning = FALSE,
                      paged.print = FALSE)
```

```{r environment}
library(tidyverse)
library(lubridate)
library(viridis)
library(scales)
library(knitr)
library(kableExtra)

theme_set(theme_bw(base_family = 18))

title <- "Mayor @billpeduto tweets"
caption <- "@conor_tompkins"
```

```{r load_data}
url <- "https://raw.githubusercontent.com/conorotompkins/pittsburgh_twitter/master/data/df_billpeduto.csv"

read_csv(url) %>% 
  mutate(created_at = with_tz(created_at, "US/Eastern"),
         date = ymd(str_sub(created_at, 1, 10)),
         year = year(date),
         month = month(date, label = TRUE),
         week = week(date),
         wday = wday(date, label = TRUE),
         hour = hour(created_at),
         month_year = str_c(month, year, sep = "-"),
         month_year = factor(month_year, levels = unique(month_year)),
         wday = factor(wday, levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))) -> df_bill

df_bill[1:5, 1:5] %>% 
  kable("html") %>% 
  kable_styling()
```

```{r date_smoothed}
df_bill %>% 
  count(date) %>%
  ggplot(aes(date, n)) +
  geom_jitter(alpha = .5) +
  geom_smooth(size = 2) +
  scale_x_date(date_breaks = "month",
               date_labels = "%b-%Y") +
  labs(title = title, 
       x = "",
       y = "Number of tweets",
       caption = caption)
```

```{r hour}
df_bill %>% 
  ggplot(aes(hour)) +
  geom_density(fill = "grey") +
  scale_x_continuous(breaks = seq(0, 23, by = 2),
                     expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(title = title,
       x = "Hour",
       y = "Number of tweets",
       caption = caption)
```

```{r weekday}
df_bill %>% 
  ggplot(aes(wday, group = 1)) +
  geom_density(stat = "count", fill = "black") +
  labs(x = "",
       y = "Number of tweets") +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(expand = c(0,0)) +
  labs(title = title,
       x = "", 
       y = "Number of tweets",
       caption = caption)
```

```{r heatmap}
df_bill %>% 
  count(wday, hour) %>% 
  complete(wday, hour = 0:23) %>% 
  replace_na(list(n = 0)) %>% 
  ggplot(aes(wday, hour, fill = n)) +
  geom_tile() +
  coord_equal() +
  scale_y_reverse(expand = c(0,0),
                  breaks = seq(0, 24, by = 3)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_fill_viridis(option = 3) +
  labs(x = "",
       y = "Hour") +
  guides(fill = guide_colorbar("Number of tweets"))
```

```{r tweet_types}
df_bill %>% 
  select(date, month_year, month, week, is_retweet, is_quote) %>% 
  mutate(tweet_type = case_when(is_retweet == FALSE & is_quote == FALSE ~ "Regular tweet",
                                   is_retweet == TRUE ~ "Retweet",
                                   is_quote == TRUE ~ "Quote")) -> df_bill_tweet_types

df_bill_tweet_types %>% 
  count(month_year, tweet_type) -> df_bill_tweet_types_month_year

df_bill_tweet_types_month_year %>%  
  ggplot(aes(month_year, n, fill = tweet_type, group = tweet_type)) +
  geom_area(position = "fill") +
  scale_fill_viridis(name = "Tweet type", discrete = TRUE) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), labels = scales::percent) +
  labs(title = "Types of @BillPeduto tweets",
       x = "",
       y = "Percentage of tweets",
       caption = caption)
```

```{r replies_heatmap}
df_bill %>% 
  filter(!is.na(reply_to_screen_name), is_quote == FALSE, is_retweet == FALSE) %>% 
  count(wday, hour) %>% 
  complete(wday, hour = 0:23) %>% 
  replace_na(list(n = 0)) %>% 
  ggplot(aes(hour, wday, fill = n)) +
  geom_tile() +
  coord_equal() +
  scale_x_continuous(expand = c(0,0),
                  breaks = seq(0, 24, by = 3)) +
  scale_y_discrete(expand = c(0,0)) +
  scale_fill_viridis(option = 3) +
  labs(x = "",
       y = "Hour") +
  guides(fill = guide_colorbar("Number of tweets"))
```


```{r, load_text_analysis_environment}
source("https://raw.githubusercontent.com/conorotompkins/pittsburgh_twitter/master/scripts/tidytext_functions.R")
set.seed(1234)
df_bill <- read_csv("https://raw.githubusercontent.com/conorotompkins/pittsburgh_twitter/master/data/bill_peduto_tweets.tweets.csv")
```

```{r munge_billpeduto_tweets}
bill_stop_words <- c("t.co", "https", "amp")

tweets_bill <- count_twitter_bigrams(df_bill, bill_stop_words)
tweets_bill %>% 
  head() %>% 
  kable("html") %>% 
  kable_styling()
```

```{r, visualize_bigrams}
visualize_bigrams(tweets_bill, 3,
                  title = "@BillPeduto tweets",
                  subtitle = "Bigram network",
                  caption = "@conor_tompkins")
```

```{r, visualize_word_correlations}
bill_stopwords <- c("t.co", "https", "amp")

bill_words <- word_correlations(df_bill, 20, bill_stopwords)

visualize_word_correlations(bill_words, 
                            title = "@BillPeduto tweets",
                            subtitle = "Word correlation network",
                            caption = "@conor_tompkins")
```
